#!/usr/bin/env python3
import click

from image_classify import run, predict


@click.group()
def cli():
    pass


@cli.command()
@click.argument('data_dir')
@click.option(
    '--model', default='densenet',
    help='Model name'
)
@click.option(
    '--epochs', default=25,
    help='Number of iteration in training process'
)
def train(data_dir, model, epochs):
    click.echo(f'train model on data "{data_dir}"')
    run.start(data_dir, model, epochs)


@cli.command()
@click.argument('image')
@click.option(
    '--checkpoint', default='checkpoint.pth',
    help='Model name'
)
def classify(image, checkpoint):
    click.echo(f'classify image "{image}"')
    guess = predict.do(image, checkpoint)
    print(guess)


if __name__ == '__main__':
    cli()
